config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  get '/users', to: 'users#index', as: 'show_users'
  
  get '/:user_name', to: 'users#show', as: 'user'
  get '/:user_name/account', to: 'users#account', as: 'account'
  post '/:user_name/new-unit', to: 'units#create', as: 'create_unit'
  get '/:user_name/new-unit', to: 'units#new', as: 'new_unit'
  get '/:user_name/:unit_name/', to: 'units#show', as: 'unit'
  
  get '/:user_name/:unit_name/edit', to: 'units#edit', as: 'edit_unit'
  patch '/:user_name/:unit_name/edit', to: 'units#patch'
  
  get '/:user_name/:unit_name/delete', to: 'units#delete', as: 'delete_unit'
  post '/:user_name/:unit_name/delete', to: 'units#destroy'
  
  post '/:user_name/:unit_name/update', to: 'units#update'
  
  get '/:user_name/:unit_name/new-variable', to: 'variables#new', as: 'new_variable'
  post '/:user_name/:unit_name/new-variable', to: 'variables#create'
  
  get '/:user_name/:unit_name/:variable_name', to: 'variables#show', as: 'variable'
  get '/:user_name/:unit_name/:variable_name/chart', to: 'variables#chart', as: 'chart'
  get '/:user_name/:unit_name/:variable_name/edit', to: 'variables#edit', as: 'edit_variable'
  patch '/:user_name/:unit_name/:variable_name/edit', to: 'variables#patch'
  get '/:user_name/:unit_name/:variable_name/delete', to: 'variables#delete', as: 'delete_variable'
  post '/:user_name/:unit_name/:variable_name/delete', to: 'variables#destroy'
  
  patch '/:user_name/:unit_name/:variable_name/update', to: 'variables#update', as: 'update_variable'
  
  #For raspberry pi communication
  post '/units/:identification', to: 'units#pi_update'


  resources :datapoints, only: [:create]
  resources :users
  resources :units, as: :unit do#, :path => '/:unit-id' do
    resources :variables, :outputs
  end
end

=begin
     pages GET    /pages(.:format)          pages#index
           POST   /pages(.:format)          pages#create
  new_page GET    /pages/new(.:format)      pages#new
 edit_page GET    /pages/:id/edit(.:format) pages#edit
      page GET    /pages/:id(.:format)      pages#show
           PATCH  /pages/:id(.:format)      pages#update
           PUT    /pages/:id(.:format)      pages#update
           DELETE /pages/:id(.:format)      pages#destroy
=end           

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :variables,  dependent: :destroy 
  has_many :pierrors,  dependent: :destroy 
  has_one :user
  
  validates :name, presence: true
  validates :plc_ip, presence: true
  validates :plc_port, presence: true
  
  def to_param
    name
  end
  
  #validates_uniqueness_of :name, allow_blank: false, scope: :user
        
  def inputs
    self.variables.where(method: 'input')
  end
  
  def outputs
    self.variables.where(method: 'output')
  end
  
  def update
    #  HTTP.post("http://#{@user.name}-#{@unit.name}.green1.co.nz")
    #  HTTP.post("#{@unit.ip}:8000")
  end
  
  def config
    ret = {'plcreader' => Hash.new, 'scadaclient' => Hash.new }
    ret['plcreader'][:variables] = self.variables.select(:name, :register_address, :length, :bit_index)
    ret['plcreader'][:plc_ip] = self.plc_ip
    ret['plcreader'][:plc_port] = self.plc_port
    
    #ret['scadaclient'][:update_period] = self.update_period
    ret
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  layout 'units'
  
  #before_action :load_unit, only: [:show, :edit, :patch]
  
  #before_action :correct_user, except: [:post_update]
  #before_action :correct_unit,   only: [:configuration, :post_update]

  def configuration
    @unit = current_user.units.find_by(name: params[:unit_name])
    render json: @unit.select(:name, :plc_ip, :plc_port).to_json
  end

  def pi_update
    @unit = Unit.find_by(identification: params[:identification])
    if @unit.psk != params[:psk]
      render json: {"error" => "Invalid passkey"}
      return
    end
    res = {}
    @unit.variables.each do |var|
      if params.key?(var.name)
        var.received_new_value(params[var.name], Time.at(params["Update_time"]))
      end
    end
    
    if params.key?('new_config') or @unit.new_config
      res['new_config'] = @unit.config
      @unit.new_config = false
      @unit.save
    end
    
    if params.key?('errors')
      if params['errors'].instance_of? Array
        params['errors'].each do |err|
          if var = @unit.variables.find_by(name: err['variable'])
            var.pierrors.build(details: err['details'], time: Time.at(params["Update_time"]))
            var.working = false
            var.save
          end
        end
      end
    end
    
    res["writes"] = @unit.variables.where(method: 'input', update_value: true).select(:name, :new_value)
    render :json => res
  end
  
  def show
    @user = current_user
    @unit = @user.units.find_by(name: params[:unit_name])
    #if request.xhr?
      #@unit.update
    #end
    
    respond_to do |format|
      format.html {render 'show'}
      format.js {render json: {"inputs" => @unit.inputs.select(:name, :current_value, :units, :working), "outputs" => @unit.outputs.select(:name, :current_value, :units, :working)}.to_json}
      format.xml  {render xml: {"inputs" => @unit.inputs.select(:name, :current_value, :units, :working), "outputs" => @unit.outputs.select(:name, :current_value, :units, :working)}}
    end
  end
  
  def new
    @unit = Unit.new
  end

  def create
    @unit = current_user.units.build(unit_params)
    @unit.save!
    #if @unit.save
    #  flash[:success] = "Unit Added"
      redirect_to current_user
    #else
    #  render 'new'
    #end
  end
  
  def delete
    @user = current_user
    @unit = @user.units.find_by(name: params[:unit_name])
  end
  
  def destroy
    @user = current_user
    @unit = @user.units.find_by(name: params[:unit_name])
    @unit.delete
    @unit.save
    redirect_to @user
  end
  
  def edit
    @user = current_user
    @unit = @user.units.find_by(name: params[:unit_name])
  end
  
  def patch
    @user = current_user
    @unit = @user.units.find_by(name: params[:unit_name])
    @unit.update(unit_params)
    redirect_to @unit
  end
  
  private
    def unit_params
      params[:unit][:name].gsub!(' ', '_')
      params.require(:unit).permit(:name, :description, :plc_ip, :plc_port, :ip, :psk, :user, :identification)
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      unless allowed_user?
        redirect_to login_url
      end
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_admin.html.erb
<section class="admin-bar">
  <%= link_to "Add Input", new_variable_url(method: 'input') %>
  <%= link_to "Add Output", new_variable_url(method: 'output') %>
  <%= link_to "Edit Unit", edit_unit_url%>
  <%= link_to "Delete Unit", delete_unit_url%>
  <%= render 'shared/admin-options' %>
</section>

app/views/units/_unit.html.erb
<%= link_to(unit_path(@user, unit), method: 'get', remote: false) do %>
  <section class="panel panel-default unit-partial">
    <section class="panel-heading">
      <%= unit.name %>
    </section>
    <section class="panel-body">
      <%= unit.description %>
    </section>
  </section>
<% end %>

app/views/units/delete.html.erb
<div class="row container">
  <div class="col-md-6 col-md-offset-3">
    Please enter the client and unit name to delete unit
    <%= form_tag do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= label_tag :user_name, "Client name" %>
      <%= text_field_tag :user_name %>

      <%= label_tag :unit_name, "Unit name" %>
      <%= text_field_tag :unit_name %>
      
      <%= submit_tag "Delete unit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/units/edit.html.erb
<div class="row container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@unit, url: edit_unit_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :plc_ip %>
      <%= f.text_field :plc_ip, class: 'form-control' %>

      <%= f.label :plc_port %>
      <%= f.text_field :plc_port, class: 'form-control' %>

      <%= f.label :short_update_period %>
      <%= f.text_field :short_update_period, class: 'form-control' %>

      <%= f.label :long_update_period %>
      <%= f.text_field :long_update_period, class: 'form-control' %>
      
      <%= f.submit "Edit unit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/units/new.html.erb
<h1>New Unit for <%= link_to current_user.name, user_url(current_user) %></h1>

<div class="row container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@unit, url: new_unit_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :plc_ip %>
      <%= f.text_field :plc_ip, class: 'form-control' %>

      <%= f.label :plc_port %>
      <%= f.text_field :plc_port, class: 'form-control' %>

      <%= f.label :identification, "Identification Number" %>
      <%= f.text_field :identification, class: 'form-control' %>

      <%= f.label :psk, "Pass key" %>
      <%= f.text_field :psk, class: 'form-control' %>
      
      <%= f.submit "Create unit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/units/show.html.erb
<% if admin? and nil %>
<section>
Identification: <%= @unit.identification %>
<br />
PassKey: <%= @unit.psk %> 
</section>
<% end %>

<% if @unit.inputs.length > 0 %>
<section id="inputs-container" class="container">
  <section class="variable-grid">
    <%= render partial: @unit.variables.where(method: 'input'), :locals => {:unit => @unit, :user => @user}%>
  </section>
</section>
<% end %>

<% if @unit.outputs.length > 0 %>
<section id="outputs-container" class="container">
  <h2>
    Outputs
  </h2>
  <section class="variable-grid">
    <%= render partial: @unit.outputs, :locals => {:unit => @unit, :user => @user} %>
  </section>
</section>

<% end %>