config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  get '/users', to: 'users#index', as: 'show_users'
  
  get '/:user_name', to: 'users#show', as: 'user'
  get '/:user_name/account', to: 'users#account', as: 'account'
  post '/:user_name/new-unit', to: 'units#create', as: 'create_unit'
  get '/:user_name/new-unit', to: 'units#new', as: 'new_unit'
  get '/:user_name/:unit_name/', to: 'units#show', as: 'unit'
  
  get '/:user_name/:unit_name/edit', to: 'units#edit', as: 'edit_unit'
  patch '/:user_name/:unit_name/edit', to: 'units#patch'
  
  get '/:user_name/:unit_name/delete', to: 'units#delete', as: 'delete_unit'
  post '/:user_name/:unit_name/delete', to: 'units#destroy'
  
  post '/:user_name/:unit_name/update', to: 'units#update'
  
  get '/:user_name/:unit_name/new-variable', to: 'variables#new', as: 'new_variable'
  post '/:user_name/:unit_name/new-variable', to: 'variables#create'
  
  get '/:user_name/:unit_name/:variable_name', to: 'variables#show', as: 'variable'
  get '/:user_name/:unit_name/:variable_name/chart', to: 'variables#chart', as: 'chart'
  get '/:user_name/:unit_name/:variable_name/edit', to: 'variables#edit', as: 'edit_variable'
  patch '/:user_name/:unit_name/:variable_name/edit', to: 'variables#patch'
  get '/:user_name/:unit_name/:variable_name/delete', to: 'variables#delete', as: 'delete_variable'
  post '/:user_name/:unit_name/:variable_name/delete', to: 'variables#destroy'
  
  patch '/:user_name/:unit_name/:variable_name/update', to: 'variables#update', as: 'update_variable'
  
  #For raspberry pi communication
  post '/units/:identification', to: 'units#pi_update'


  resources :datapoints, only: [:create]
  resources :users
  resources :units, as: :unit do#, :path => '/:unit-id' do
    resources :variables, :outputs
  end
end

=begin
     pages GET    /pages(.:format)          pages#index
           POST   /pages(.:format)          pages#create
  new_page GET    /pages/new(.:format)      pages#new
 edit_page GET    /pages/:id/edit(.:format) pages#edit
      page GET    /pages/:id(.:format)      pages#show
           PATCH  /pages/:id(.:format)      pages#update
           PUT    /pages/:id(.:format)      pages#update
           DELETE /pages/:id(.:format)      pages#destroy
=end           

app/models/variable.rb
class Variable < ApplicationRecord
  belongs_to :unit
  has_many :pierrors, dependent: :destroy 
  
  validates :method, inclusion: { in: ['input', 'output'],
      message: "must be input or output" }
  
  validates :register_address, numericality: { 
              :only_integer => true, 
              :greater_than => 40000,
              :less_than => 50000, 
              :message => "requires integer between 40001 and 49999" }
  
  after_create :generateTimeSeries
  
  # retrieves mongodb object
  def data
    TimeSeries.find_by(name: self.dataName)
  end
  
  def received_new_value(value, time)
    self.working = true
    if value
      self.current_value = value
      if value == self.new_value
        self.update_value = false
      end
    
      self.data.new_value(value, Time.at(time))
    
      self.save
    end
  end
  
  def last_error
  end
  
  def to_param
    name
  end
  
  private
    def generateTimeSeries
      TimeSeries.create(name: self.dataName, time: Time.now)
      print("
      CREATED DATA
      ")
    end
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  layout 'units'
  
  def show
    @unit = current_user.units.find_by(name: params[:unit_name])
    @variable = @unit.variables.find_by(name: params[:variable_name])
    if @variable.working == false
      @error = @variable.pierrors.last
    end
  end
  
  def new
    @unit  = Unit.find_by(name: params[:unit_name])
    @variable = @unit.variables.new
  end
  
  def chart
    @unit = current_user.units.find_by(name: params[:unit_name])
    @variable = @unit.variables.find_by(name: params[:variable_name])
    period = params[:period]
    from = Time.new(2017, 11, 27, 23, 30) #params[:from]
    
    if period == "days"
      data = @variable.data.days(from) 
    elsif period == "hours"
      data = @variable.data.hours(from) 
    elsif period == "mins"
      data = @variable.data.mins(from) 
    elsif period == "secs"
      data = @variable.data.secs(from) 
    end

    respond_to do |format|
      format.html { render html: draw(data, period, from), layout: false }
      format.json { render json: data }
    end
    
  end
  
  def create
    @unit = Unit.find_by(name: params[:unit_name])
    @variable = @unit.variables.build(variable_params)
    @variable.dataName = params[:user_name] + "-" + params[:unit_name] + "-" + @variable.name
    if @variable.save
      flash[:success] = "Variable Successfully created"
      @unit.new_config = true
      @unit.save
      redirect_to unit_url(current_user, @unit)
    else
      render 'new', :method => params[:method]
    end
  end
  
  def edit
    @unit  = current_user.units.find_by(name: params[:unit_name])
    @variable = @unit.variables.find_by(name: params[:variable_name])
  end
  
  def patch
    @unit  = current_user.units.find_by(name: params[:unit_name])
    @variable = @unit.variables.find_by(name: params[:variable_name])
    if @variable.update(variable_params)
      @unit.new_config = true
      @unit.save
    end
    redirect_to variable_url(current_user, @unit, @variable)
  end
  
  def delete
    @user = current_user
    @unit = @user.units.find_by(name: params[:unit_name])
    @variable = @unit.variables.find_by(name: params[:variable_name])
  end
  
  def destroy
    @user = current_user
    @unit = @user.units.find_by(name: params[:unit_name])
    @variable = @unit.variables.find_by(name: params[:variable_name])
    unless params[:given_user_name] == "imsure" or (@user.name == params[:given_user_name] and @unit.name == params[:given_unit_name] and @variable.name == params[:given_variable_name])
      flash[:danger] = "Wrong variables details"
      redirect_to delete_variable_url(@user, @unit, @variable)
    else
      @variable.delete
      @variable.save
      @unit.new_config = true
      @unit.save
      redirect_to unit_url(@user, @unit)
    end
  end
  
  def update
      @unit  = Unit.find_by(name: params[:unit_name])
      @variable = @unit.variables.find_by(name: params[:variable_name])
     
      @variable.update(update_value: true, new_value: params[:variable][:new_value])
       
      respond_to do |format|
        if @variable.save
          print("
          SAVED
          ")
          format.html { redirect_to @user}
          format.js
          format.json { render json: @variable, status: :updated, location: @variable }
        else
          format.html { render action: "update" }
          format.json { render json: @variable.errors, status: :unprocessable_entity }
        end
      end
  end
  
  private
    def variable_params
      params[:variable][:name].gsub!(' ', '_')
      params.require(:variable).permit(:name, :register_address, :bit_index, :length, :units, :unit_id, :method)
    end
    
    def update_params
      params.require(:new_value)
    end
    
    def draw(data, period, from)
    
      if @variable.units != "boolean"
        units = " (#{@variable.units})"
      else
        units = nil
      end
  
      line_chart chart_url({period: period, from: from}), refresh: 300, library: {
        scales: {
          yAxes: [
            {
              display: true,
              reverse: true,
              scaleLabel:{
                display: true,
                labelString: "#{@variable.name.gsub('_', ' ')}#{units}"
              }
            }
          ],
          xAxes: [
            time: {
              max: Time.now,
              min: from
            }
          ]
        }
      }
    end
end

app/helpers/variables_helper.rb
module VariablesHelper
  
end

app/views/variables/_admin.html.erb
<nav class="admin-bar">
  <%= link_to "Edit Variable", edit_variable_path %>
  <%= link_to "Delete Variable", delete_variable_path %>
  <%= render 'shared/admin-options' %>
</nav>

app/views/variables/_error_messages.html.erb
<% if @variable and @variable.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@variable.errors.count, "error") %>.
    </div>
    <ul>
    <% @variable.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/variables/_variable.html.erb
<% if variable.method == 'output' %>
<section id="variable-<%= variable.name %>" class="output panel panel-default variable col-md-4">
  <%= link_to(variable_path(@user, @unit, variable)) do %>
    <div class="name panel-heading">
      <%= strip(variable.name)%> <!--.sub!('_', ' ')%> -->
    </div>
  <% end %>
  <div class="panel-body">
    <section>
    <span id="<%= variable.name %>-value">
    <br>
    </span>
    </section>
  </div>
</section>

<% else %>
<section  id="variable-<%= variable.name %>" class="variable input panel panel-default col-md-2">
  <section class="input-title">
  <% if variable.units == 'boolean' %>
    <% [' On', ' on', ' Off', 'off'].each do |str| %>
      <% if variable.name.gsub('_', ' ').end_with?(str) %>
        <%= @formatedName = variable.name.gsub('_', ' ').chomp(str) %>
      <% end %>
    <% end %>
    is 
    <span id="<%= variable.name %>-value">
    <br>
    </span>
  <% else %>
    <%= variable.name.gsub('_', ' ') %>
    is
    <%= variable.current_value %>
    <%= variable.units %>
  <% end %>
  </section>
  <section class="change-form">
      <% if variable.units == "boolean" and nil %>
        <%= form_with(model: [@unit, variable], url: update_variable_url(@user, @unit, variable)) do |f| %>
          <%= hidden_field_tag :unit_id, unit.id %>
          <%= hidden_field_tag :new_value, -1 %>
          <%= f.submit "Switch #{@formatedName}"%>
        <% end %>
      <% else %>
        <%= form_with(model: [@unit, variable], url: update_variable_url(@user, @unit, variable)) do |f| %>
          <%= f.text_field :new_value %>
          <%= hidden_field_tag :unit_id, unit.id %>
          <%= f.submit "Update"%>
        <% end %>
      <% end %>
      <%= link_to(variable_path(@user, @unit, variable)) do %>
      <%= 'more' %>
      <% end %>
  </section>
</section>
<% end %>

app/views/variables/delete.html.erb
<div class="row container">
  <div class="col-md-6 col-md-offset-3">
    Please enter the client, unit, and variable name to delete variable
    <%= form_tag do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= label_tag :given_user_name, "Client name" %>
      <%= text_field_tag :given_user_name %>

      <%= label_tag :given_unit_name, "Unit name" %>
      <%= text_field_tag :given_unit_name %>
      
      <%= label_tag :given_variable_name, "Variable name" %>
      <%= text_field_tag :given_variable_name %>
      
      <%= submit_tag "Delete variable", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/variables/edit.html.erb
<h1>Edit Variable</h1>

<div class="row container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@variable, url: edit_variable_path) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :register_address %>
      <%= f.text_field :register_address %>
      
      <%= f.label :bit_index%>
      <%= f.text_field :bit_index %>
      
      <%= f.label :length%>
      <%= f.text_field :length %>
      
      <%= f.label :units%>
      <%= f.text_field :units %>
      
      <%= f.submit "edit variable", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/variables/new.html.erb
<h1>New Variable</h1>

<div class="row container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@variable, url: new_variable_path(:method => params[:method])) do |f| %>
      <%= render 'error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :register_address %>
      <%= f.text_field :register_address %>
      
      <%= f.label :bit_index%>
      <%= f.text_field :bit_index %>
      
      <%= f.label :length, "Number of bits (16 per holding register)"%>
      <%= f.text_field :length %>
      
      <%= f.label :units%>
      <%= f.text_field :units %>
    
      <%= f.hidden_field :method, :value => params[:method]||=nil %>
      
      <%= f.submit "Create variable", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/variables/show.html.erb
<h2>
  <%= strip(@variable.name) %>
</h2>

<section class="variable">
<span id="<%= @variable.name %>-value">
<br>
</span>
<div id="chart">

</div>
</section>
<section>
  <%= render @error if @error %>
</section>