config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  get '/users', to: 'users#index', as: 'show_users'
  
  get '/:user_name', to: 'users#show', as: 'user'
  get '/:user_name/account', to: 'users#account', as: 'account'
  post '/:user_name/new-unit', to: 'units#create', as: 'create_unit'
  get '/:user_name/new-unit', to: 'units#new', as: 'new_unit'
  get '/:user_name/:unit_name/', to: 'units#show', as: 'unit'
  
  get '/:user_name/:unit_name/edit', to: 'units#edit', as: 'edit_unit'
  patch '/:user_name/:unit_name/edit', to: 'units#patch'
  
  get '/:user_name/:unit_name/delete', to: 'units#delete', as: 'delete_unit'
  post '/:user_name/:unit_name/delete', to: 'units#destroy'
  
  post '/:user_name/:unit_name/update', to: 'units#update'
  
  get '/:user_name/:unit_name/new-variable', to: 'variables#new', as: 'new_variable'
  post '/:user_name/:unit_name/new-variable', to: 'variables#create'
  
  get '/:user_name/:unit_name/:variable_name', to: 'variables#show', as: 'variable'
  get '/:user_name/:unit_name/:variable_name/chart', to: 'variables#chart', as: 'chart'
  get '/:user_name/:unit_name/:variable_name/edit', to: 'variables#edit', as: 'edit_variable'
  patch '/:user_name/:unit_name/:variable_name/edit', to: 'variables#patch'
  get '/:user_name/:unit_name/:variable_name/delete', to: 'variables#delete', as: 'delete_variable'
  post '/:user_name/:unit_name/:variable_name/delete', to: 'variables#destroy'
  
  patch '/:user_name/:unit_name/:variable_name/update', to: 'variables#update', as: 'update_variable'
  
  #For raspberry pi communication
  post '/units/:identification', to: 'units#pi_update'


  resources :datapoints, only: [:create]
  resources :users
  resources :units, as: :unit do#, :path => '/:unit-id' do
    resources :variables, :outputs
  end
end

=begin
     pages GET    /pages(.:format)          pages#index
           POST   /pages(.:format)          pages#create
  new_page GET    /pages/new(.:format)      pages#new
 edit_page GET    /pages/:id/edit(.:format) pages#edit
      page GET    /pages/:id(.:format)      pages#show
           PATCH  /pages/:id(.:format)      pages#update
           PUT    /pages/:id(.:format)      pages#update
           DELETE /pages/:id(.:format)      pages#destroy
=end           

app/models/output.rb
class Output < ApplicationRecord
  belongs_to :unit
  has_many :datapoints
  
  def update_current_value(value, time)
    self.current_value = value
    if ((time - self.last_update)).to_i >= 15
      self.datapoints.create(value: value, read_at: time)
      self.last_update = time
    end
    self.save
  end
  
  def to_param
    name
  end
end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController
 
  before_action :correct_user
  
  def create
    @unit = current_user.units.find_by(name: params[:unit_name])
    @output = @unit.outputs.build(output_params)
    if @output.save
      redirect_to @unit
    else
      redirect_to @unit
    end
  end
  
  def edit
    @unit  = current_user.units.find_by(name: params[:unit_name])
    @output = @unit.outputs.find_by(name: params[:output_name])
  end
  
  def patch
    @unit  = current_user.units.find_by(name: params[:unit_name])
    @output = @unit.outputs.find_by(name: params[:output_name])
    @output.update(output_params)
    redirect_to @unit
  end
  
  def show
    @unit  = current_user.units.find_by(name: params[:unit_name])
    @output = @unit.outputs.find_by(name: params[:output_name])
  end
  
  def new
    @unit  = current_user.units.find_by(name: params[:unit_name])
    @output = @unit.outputs.new
  end
  
  private
    def output_params
      params.require(:output).permit(:name, :register_address, :bit_index, :length, :units, :unit_id)
    end
    
    def correct_user
      unless allowed_user?
        redirect_to login_url
      end
    end
end
class OutputsController < ApplicationController
 
  before_action :correct_user
  
  def create
    @unit = current_user.units.find_by(name: params[:unit_name])
    @output = @unit.outputs.build(output_params)
    if @output.save
      redirect_to @unit
    else
      redirect_to @unit
    end
  end
  
  def show
    @unit  = current_user.units.find_by(name: params[:unit_name])
    @output = @unit.outputs.find_by(name: params[:output_name])
  end
  
  def new
    @unit  = current_user.units.find_by(name: params[:unit_name])
    @output = @unit.outputs.new
  end
  
  private
    def output_params
      params.require(:output).permit(:name, :register_address, :bit_index, :length, :units, :unit_id)
    end
    
    def correct_user
      unless allowed_user?
        redirect_to login_url
      end
    end
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/views/outputs/_output.html.erb
<section id="output-<%= output.id %>" class="panel panel-default variable col-md-4">
  <div class="name panel-heading">
    <%= output.name%> <!--.sub!('_', ' ')%> -->
  </div>
  <div class="panel-body">
    <section>
    <span id="<%= output.name %>-value">
      <br>
    </span>
    </section>
  </div>
  <!--<div class="panel-footer">
  </div>-->
</section>

app/views/outputs/edit.html.erb
<h1>Edit <%= link_to @output.name %></h1>

<div class="row container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@output, url: edit_output_path) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :register_address %>
      <%= f.text_field :register_address %>
      
      <%= f.label :bit_index%>
      <%= f.text_field :bit_index %>
      
      <%= f.label :length%>
      <%= f.text_field :length %>
      
      <%= f.label :units%>
      <%= f.text_field :units %>
      
      <%= f.submit "Edit unit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/outputs/new.html.erb
<section id="new_output_form">
  <%= form_for(@output, url: new_user_unit_output_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :register_address %>
  <%= f.text_field :register_address %>
  <br>
  <%= f.label :bit_index%>
  <%= f.text_field :bit_index %>
  <br>
  <%= f.label :length%>
  <%= f.text_field :length %>
  <br>
  <%= f.label :units%>
  <%= f.text_field :units %>
  <br>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</section>

app/views/outputs/show.html.erb
<%= @output.datapoints.length %>
<%= line_chart @output.datapoints.group_by_minute(:read_at).maximum(:value) %>