config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  get '/users', to: 'users#index', as: 'show_users'
  
  get '/:user_name', to: 'users#show', as: 'user'
  get '/:user_name/account', to: 'users#account', as: 'account'
  post '/:user_name/new-unit', to: 'units#create', as: 'create_unit'
  get '/:user_name/new-unit', to: 'units#new', as: 'new_unit'
  get '/:user_name/:unit_name/', to: 'units#show', as: 'unit'
  
  get '/:user_name/:unit_name/edit', to: 'units#edit', as: 'edit_unit'
  patch '/:user_name/:unit_name/edit', to: 'units#patch'
  
  get '/:user_name/:unit_name/delete', to: 'units#delete', as: 'delete_unit'
  post '/:user_name/:unit_name/delete', to: 'units#destroy'
  
  post '/:user_name/:unit_name/update', to: 'units#update'
  
  get '/:user_name/:unit_name/new-variable', to: 'variables#new', as: 'new_variable'
  post '/:user_name/:unit_name/new-variable', to: 'variables#create'
  
  get '/:user_name/:unit_name/:variable_name', to: 'variables#show', as: 'variable'
  get '/:user_name/:unit_name/:variable_name/chart', to: 'variables#chart', as: 'chart'
  get '/:user_name/:unit_name/:variable_name/edit', to: 'variables#edit', as: 'edit_variable'
  patch '/:user_name/:unit_name/:variable_name/edit', to: 'variables#patch'
  get '/:user_name/:unit_name/:variable_name/delete', to: 'variables#delete', as: 'delete_variable'
  post '/:user_name/:unit_name/:variable_name/delete', to: 'variables#destroy'
  
  patch '/:user_name/:unit_name/:variable_name/update', to: 'variables#update', as: 'update_variable'
  
  #For raspberry pi communication
  post '/units/:identification', to: 'units#pi_update'


  resources :datapoints, only: [:create]
  resources :users
  resources :units, as: :unit do#, :path => '/:unit-id' do
    resources :variables, :outputs
  end
end

=begin
     pages GET    /pages(.:format)          pages#index
           POST   /pages(.:format)          pages#create
  new_page GET    /pages/new(.:format)      pages#new
 edit_page GET    /pages/:id/edit(.:format) pages#edit
      page GET    /pages/:id(.:format)      pages#show
           PATCH  /pages/:id(.:format)      pages#update
           PUT    /pages/:id(.:format)      pages#update
           DELETE /pages/:id(.:format)      pages#destroy
=end           

app/helpers/layouts_helper.rb
module LayoutsHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/_adminBar.html.erb
<section class="admin-bar">
  <% if @variable %>
    <% if @variable.name and params.key?(:variable_name) %>
      <%= link_to "Edit Variable", edit_variable_path %>
      <%= link_to "Delete Variable", delete_variable_path %>
    <% end %>
  <% elsif @unit %>  
    <% if @unit.name %>
      <%= link_to "Add Input", new_variable_url(method: 'input') %>
      <%= link_to "Add Output", new_variable_url(method: 'output') %>
      <%= link_to "Edit Unit", edit_unit_url%>
      <%= link_to "Delete Unit", delete_unit_url%>
    <% end %>
  <% elsif @user %>
    <% if @user.name %>
      <%= link_to "Add unit", new_unit_url(@user.name) %>
    <% else %>
      <%= link_to "New User", signup_url %>
    <% end %>
  <% end %>
  <%= link_to "All Users", show_users_url %>
</section>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SCADA test", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= 
        if logged_in?
          link_to "Units", user_url(current_user)
        else
          link_to "Home",   root_url 
        end
        %></li>
        <li><%= link_to "Help",   '#' %></li>        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Account", account_url(current_user) %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<nav id="sidebar" class="navbar col-s-1">
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Units", user_path(current_user) %></li>
    <li><a href=units_url>Units</a></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/adminBar' if admin? %>
    <section class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </section>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/units.html.erb
<% if @unit.name %>
  <section id="unit-header">
    <%= link_to(unit_url(current_user, @unit)) do %>
      <h1>
        <%= @unit.name.gsub('_', ' ') %>
      </h1>
    <% end %>
    <p class="col-md-4">
      <%= @unit.description %>
    </p>
  </section>
<% end %>

<section>
  <%= yield %>
</section>

<% parent_layout "application" %>

app/views/layouts/users.html.erb
<section class="jumbotron">
  <h1>
    User: <%= @user.name %>
  </h1>

 <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Add Unit", new_unit_variable_url(unit_id: @user.id), method: 'get'%></li>
    </ul>
  </nav>
</section>
<section>
<%= yield %>
</section>

<% parent_layout "application" %>